name: spotitem
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: '^0.11.3+14'
  shared_preferences: '^0.3.1'
  package_info: '^0.1.1'
  image_picker: '^0.2.1'
  location: '^1.1.7'
  qrcode_reader: '^0.3.2'
  url_launcher: '^2.0.1'
  google_sign_in: '^2.0.1'
  firebase_messaging: '^0.1.2'
  firebase_analytics: '^0.2.1'
  google_maps_webservice: '^0.0.3'
  flutter_google_places_autocomplete: '^0.0.3+1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
    - assets/logo.png
    - assets/jeux.png
    - assets/bebe_jeunesse.png
    - assets/cuisine.png
    - assets/garage.png
    - assets/jardin.png
    - assets/objet.png
    - assets/fete.png