name: spotitem
dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+14'
  fluro: 
    path: '../fluro'
  shared_preferences: '>=0.2.5'
  image_picker: '>=0.1.1'
  location: '>=1.1.4'
  url_launcher: '>=0.4.0'
  web_socket_channel: '>=1.0.5'
  google_sign_in: '>=0.3.1'
  intl: '>=0.14.0 <0.16.0'
  intl_translation: '>=0.14.0 <0.16.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
    - assets/logo.png
    - assets/jeux.png
    - assets/bebe_jeunesse.png
    - assets/cuisine.png
    - assets/garage.png
    - assets/jardin.png
    - assets/objet.png
    - assets/fete.png